name: On Push
on: push

jobs:
  run_test:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['25.3']
        elixir: ['1.14.3']
    env:
      RUSTLER_PRECOMPILATION_BIOMEJS_BUILD: "1"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Clone biome repo
        shell: bash
        run: |
          bash ./clone-biome.sh

      - run: mix deps.get
      - name: Apply ruster hotfix
        shell: bash
        run: |
          sh hotfix.sh
      - run: mix test
